apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    app: api
spec:
  containers:
  - name: helloworld-api
    image: docker.pkg.github.com/sam-atkins/helloworldapi/helloworldapi:0.1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  imagePullSecrets:
  - name: dockerconfigjson-github-com
