apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: docker.pkg.github.com/sam-atkins/helloworldapi/helloworldapi:0.2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
      imagePullSecrets:
        - name: dockerconfigjson-github-com
